FROM golang:latest
WORKDIR /app
COPY go.mod go.sum /app/
RUN go mod download
RUN go get github.com/githubnemo/CompileDaemon
ENTRYPOINT CompileDaemon --build="go build -o server cli/server/main.go" --command="./server"