version: '3.5'
services:
  db:
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test_db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -path=/migrations -database postgres://user:password@db:5432/test_db?sslmode=disable up